language: c

compiler:
  - clang
  - gcc

sudo: false

install:
  - ./script/build.sh -DCMAKE_INSTALL_PREFIX=$HOME/local
  - ./script/install.sh

script:
  - bekobrew --version
  - bekobrew install
  - ./build/run_test

env:
  - PATH=$PATH:$HOME/local/bin

cache:
  directories:
    - vendor/
    - build/
