#!/bin/bash

function build_master() {
  make publish_bekobrew
}

function build_installer() {
  make publish_installer
}

function build_gh_pages() {
  build_installer
}

case ${TRAVIS_BRANCH} in

"master") build_master && build_gh_pages ;

esac

