#!/bin/bash

# mirroring: sh19910711/master => u-aizu/bekobrew
git push --quiet https://${GITHUB_TOKEN}@github.com/u-aizu/bekobrew.git master:bekobrew

# update bekobrew command on u-aizu/master
local bekobrew_master_dir=tmp/bekobrew-master
git clone --single-branch -b master git://github.com/u-aizu/bekobrew.git ${bekobrew_master_dir}
mkdir -p ${bekobrew_master_dir}/bin/ || true
cp tmp/bekobrew ${bekobrew_master_dir}/bin/bekobrew
pushd ${bekobrew_master_dir}
git add bin/
git commit --allow-empty -m "update bekobrew command"
git tag ${BEKOBREW_VERSION}
git push --quiet https://${GITHUB_TOKEN}@github.com/u-aizu/bekobrew.git master ${BEKOBREW_VERSION}
popd

